// ════════════════════════════════════════════════════════════════
// Leave Approval Service — approve, reject, bulk (Manager ops)
// ════════════════════════════════════════════════════════════════

import { prisma } from "@/lib/prisma";
import { writeAuditLog } from "@/lib/audit/logger";
import { DomainError, ErrorCodes } from "@/lib/api/errors";
import type { Caller, RequestMeta } from "@/lib/api/types";

export async function getPendingForApprover(
  caller: Caller,
  page: number,
  perPage: number,
) {
  const where = { approverId: caller.employeeId, status: "PENDING" as const };

  const [items, total] = await Promise.all([
    prisma.leaveRequest.findMany({
      where,
      include: {
        employee: {
          select: {
            firstNameTh: true,
            lastNameTh: true,
            employeeCode: true,
          },
        },
      },
      orderBy: { createdAt: "asc" },
      skip: (page - 1) * perPage,
      take: perPage,
    }),
    prisma.leaveRequest.count({ where }),
  ]);

  return { items, total, page, perPage };
}

export async function approveLeaveRequest(
  caller: Caller,
  id: string,
  meta: RequestMeta,
) {
  const result = await prisma.$transaction(async (tx) => {
    const request = await tx.leaveRequest.findUnique({ where: { id } });
    if (!request) throw new DomainError(ErrorCodes.RECORD_NOT_FOUND, {}, 404);
    if (request.status !== "PENDING") {
      throw new DomainError(ErrorCodes.ALREADY_PROCESSED);
    }
    if (request.approverId !== caller.employeeId) {
      throw new DomainError(ErrorCodes.NOT_APPROVER, {}, 403);
    }

    // Move pending → used in quota
    if (request.quotaLockedId) {
      await tx.leaveQuota.update({
        where: { id: request.quotaLockedId },
        data: {
          pendingDays: { decrement: request.daysRequested.toNumber() },
          usedDays: { increment: request.daysRequested.toNumber() },
        },
      });
    }

    const updated = await tx.leaveRequest.update({
      where: { id },
      data: { status: "APPROVED", approvedAt: new Date() },
    });

    // Cascade approve to auto-generated overflow children (e.g. SICK→LWP split)
    const children = await tx.leaveRequest.findMany({
      where: { parentRequestId: id, autoGenerated: true, status: "PENDING" },
    });
    for (const child of children) {
      await tx.leaveRequest.update({ where: { id: child.id }, data: { status: "APPROVED", approvedAt: new Date() } });
      await writeAuditLog({ actorId: caller.userId, action: "leave.approve_cascade", entityType: "LeaveRequest", entityId: child.id, before: child, after: { ...child, status: "APPROVED" }, ipAddress: meta.ip, userAgent: meta.userAgent }, tx);
    }

    await writeAuditLog({ actorId: caller.userId, action: "leave.approve", entityType: "LeaveRequest", entityId: id, before: request, after: updated, ipAddress: meta.ip, userAgent: meta.userAgent }, tx);

    return updated;
  });

  import("@/lib/email/leave-notification-sender")
    .then((m) => m.notifyLeaveDecision(id, "APPROVED"))
    .catch(console.error);

  return result;
}

export async function rejectLeaveRequest(
  caller: Caller,
  id: string,
  reason: string,
  meta: RequestMeta,
) {
  const result = await prisma.$transaction(async (tx) => {
    const request = await tx.leaveRequest.findUnique({ where: { id } });
    if (!request) throw new DomainError(ErrorCodes.RECORD_NOT_FOUND, {}, 404);
    if (request.status !== "PENDING") {
      throw new DomainError(ErrorCodes.ALREADY_PROCESSED);
    }
    if (request.approverId !== caller.employeeId) {
      throw new DomainError(ErrorCodes.NOT_APPROVER, {}, 403);
    }

    // Release pending quota
    if (request.quotaLockedId) {
      await tx.leaveQuota.update({
        where: { id: request.quotaLockedId },
        data: {
          pendingDays: { decrement: request.daysRequested.toNumber() },
        },
      });
    }

    const updated = await tx.leaveRequest.update({
      where: { id },
      data: { status: "REJECTED", rejectedReason: reason },
    });

    // Cascade reject to auto-generated overflow children
    const children = await tx.leaveRequest.findMany({
      where: { parentRequestId: id, autoGenerated: true, status: "PENDING" },
    });
    for (const child of children) {
      await tx.leaveRequest.update({ where: { id: child.id }, data: { status: "REJECTED", rejectedReason: reason } });
      await writeAuditLog({ actorId: caller.userId, action: "leave.reject_cascade", entityType: "LeaveRequest", entityId: child.id, before: child, after: { ...child, status: "REJECTED" }, reason, ipAddress: meta.ip, userAgent: meta.userAgent }, tx);
    }

    await writeAuditLog({ actorId: caller.userId, action: "leave.reject", entityType: "LeaveRequest", entityId: id, before: request, after: updated, reason, ipAddress: meta.ip, userAgent: meta.userAgent }, tx);

    return updated;
  });

  import("@/lib/email/leave-notification-sender")
    .then((m) => m.notifyLeaveDecision(id, "REJECTED"))
    .catch(console.error);

  return result;
}

export async function bulkDecision(
  caller: Caller,
  ids: string[],
  decision: "APPROVED" | "REJECTED",
  reason: string | undefined,
  meta: RequestMeta,
) {
  const results: { id: string; ok: boolean; error?: string }[] = [];
  for (const id of ids) {
    try {
      if (decision === "APPROVED") {
        await approveLeaveRequest(caller, id, meta);
      } else {
        await rejectLeaveRequest(caller, id, reason ?? "", meta);
      }
      results.push({ id, ok: true });
    } catch (err) {
      results.push({
        id,
        ok: false,
        error: err instanceof Error ? err.message : "Unknown error",
      });
    }
  }
  return results;
}

