// ════════════════════════════════════════════════════════════════
// Leave Query Service — read-only queries (list, detail, preview)
// ════════════════════════════════════════════════════════════════

import { getPrisma } from "@/lib/prisma";
import { DomainError, ErrorCodes } from "@/lib/api/errors";
import { calculateWorkingDays } from "./working-days";
import { isSensitiveDataRole } from "@/lib/security/role-helpers";
import type { Role } from "@prisma/client";
import type { LeavePreviewInput, LeaveFilters } from "./schemas";

export async function previewLeave(
  employeeId: string,
  input: LeavePreviewInput,
) {
  const startDate = new Date(input.startDate);
  const endDate = new Date(input.endDate);
  const prisma = await getPrisma();

  // Quota lookup is skipped for unpaid leave; overlap check always runs.
  // Auto-generated overflow children are excluded — they're internal
  // bookkeeping and would double-count.
  const quotaPromise = input.leaveType !== "LEAVE_WITHOUT_PAY"
    ? prisma.leaveQuota.findFirst({
        where: { employeeId, leaveType: input.leaveType, quotaYear: startDate.getFullYear() },
      })
    : Promise.resolve(null);

  const overlapPromise = prisma.leaveRequest.findFirst({
    where: {
      employeeId,
      autoGenerated: false,
      status: { in: ["PENDING", "APPROVED"] },
      startDate: { lte: endDate },
      endDate: { gte: startDate },
    },
    select: { id: true, startDate: true, endDate: true, status: true, leaveType: true },
  });

  const [days, quota, overlapping] = await Promise.all([
    calculateWorkingDays(startDate, endDate, input.halfDay),
    quotaPromise,
    overlapPromise,
  ]);

  let available: number | null = null;
  let sufficient = true;
  if (input.leaveType !== "LEAVE_WITHOUT_PAY") {
    if (quota) {
      available = quota.allocatedDays
        .minus(quota.usedDays)
        .minus(quota.pendingDays)
        .toNumber();
      sufficient = available >= days;
    } else {
      available = 0;
      sufficient = false;
    }
  }

  return {
    days,
    available,
    sufficient,
    leaveType: input.leaveType,
    overlap: overlapping
      ? {
          id: overlapping.id,
          startDate: overlapping.startDate.toISOString().slice(0, 10),
          endDate: overlapping.endDate.toISOString().slice(0, 10),
          status: overlapping.status,
          leaveType: overlapping.leaveType,
        }
      : null,
  };
}

export async function getMyLeaveRequests(
  employeeId: string,
  filters: LeaveFilters,
) {
  const prisma = await getPrisma();
  const where = {
    employeeId,
    ...(filters.status && { status: filters.status }),
    ...(filters.leaveType && { leaveType: filters.leaveType }),
    ...(filters.year && {
      startDate: {
        gte: new Date(`${filters.year}-01-01`),
        lte: new Date(`${filters.year}-12-31`),
      },
    }),
  };

  const [items, total] = await Promise.all([
    prisma.leaveRequest.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip: (filters.page - 1) * filters.perPage,
      take: filters.perPage,
    }),
    prisma.leaveRequest.count({ where }),
  ]);

  return { items, total, page: filters.page, perPage: filters.perPage };
}

export async function getLeaveRequestDetail(
  id: string,
  caller: { employeeId: string; roles: Role[] },
) {
  const prisma = await getPrisma();
  const request = await prisma.leaveRequest.findUnique({
    where: { id },
    include: {
      employee: {
        select: {
          id: true,
          firstNameTh: true,
          lastNameTh: true,
          employeeCode: true,
          managerId: true,
        },
      },
      approver: {
        select: { id: true, firstNameTh: true, lastNameTh: true },
      },
    },
  });

  if (!request) {
    throw new DomainError(ErrorCodes.RECORD_NOT_FOUND, {}, 404);
  }

  // Ownership check: owner, approver, direct manager, or HR
  const isOwner = request.employeeId === caller.employeeId;
  const isApprover = request.approverId === caller.employeeId;
  const isManager = request.employee.managerId === caller.employeeId;
  const isHR = isSensitiveDataRole(caller.roles);
  if (!isOwner && !isApprover && !isManager && !isHR) {
    throw new DomainError(ErrorCodes.NOT_OWNER, {}, 403);
  }

  return request;
}

export async function getTeamCalendar(
  caller: { employeeId: string; roles?: Role[] },
  month: number,
  year: number,
) {
  const prisma = await getPrisma();
  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0);

  // HR roles see all employees, managers see only their team
  const isHR = caller.roles ? isSensitiveDataRole(caller.roles) : false;

  let employeeFilter: { in: string[] } | undefined;
  if (!isHR) {
    const subordinates = await prisma.employee.findMany({
      where: { managerId: caller.employeeId },
      select: { id: true },
    });
    employeeFilter = { in: [caller.employeeId, ...subordinates.map((s) => s.id)] };
  }

  return prisma.leaveRequest.findMany({
    where: {
      ...(employeeFilter && { employeeId: employeeFilter }),
      status: { in: ["PENDING", "APPROVED"] },
      autoGenerated: false, // exclude overflow children (shown as part of parent)
      startDate: { lte: endDate },
      endDate: { gte: startDate },
    },
    include: {
      employee: {
        select: { id: true, firstNameTh: true, lastNameTh: true, employeeCode: true },
      },
    },
    orderBy: { startDate: "asc" },
  });
}

/**
 * Personal leave calendar for an employee for a given month, including:
 *   - own leave requests (PENDING / APPROVED / REJECTED visible so the user
 *     can see denied requests on the calendar context)
 *   - public holidays in the same month
 */
export async function getEmployeeCalendar(employeeId: string, month: number, year: number) {
  const prisma = await getPrisma();
  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0);

  const [requests, holidays] = await Promise.all([
    prisma.leaveRequest.findMany({
      where: {
        employeeId,
        autoGenerated: false,
        startDate: { lte: endDate },
        endDate: { gte: startDate },
      },
      orderBy: { startDate: "asc" },
    }),
    prisma.publicHoliday.findMany({
      where: { date: { gte: startDate, lte: endDate } },
      orderBy: { date: "asc" },
    }),
  ]);

  return { requests, holidays };
}
