import { Decimal } from "@prisma/client/runtime/library";
import { writeAuditLog } from "@/lib/audit/logger";
import type { LeaveHalfDay } from "@prisma/client";
import type { Caller, RequestMeta } from "@/lib/api/types";

type TxClient = Parameters<Parameters<typeof import("@/lib/prisma").prisma.$transaction>[0]>[0];

interface OverflowInput {
  startDate: Date;
  endDate: Date;
  halfDay: LeaveHalfDay;
  reason: string;
}

interface OverflowResult {
  request: { id: string; [key: string]: unknown };
  overflow: { id: string; [key: string]: unknown } | null;
}

/**
 * Handle SICK leave submission with automatic LWP overflow.
 * - If SICK available >= requested → normal SICK request
 * - If SICK available > 0 but < requested → split: parent SICK + child LWP
 * - If SICK available === 0 → plain LWP request (no auto-generation)
 */
export async function submitSickWithOverflow(
  tx: TxClient,
  caller: Caller,
  input: OverflowInput,
  totalDays: Decimal,
  sickQuota: { id: string; allocatedDays: Decimal; usedDays: Decimal; pendingDays: Decimal },
  meta: RequestMeta,
): Promise<OverflowResult> {
  const available = sickQuota.allocatedDays
    .minus(sickQuota.usedDays)
    .minus(sickQuota.pendingDays);

  const employee = await tx.employee.findUnique({
    where: { id: caller.employeeId },
    select: { managerId: true },
  });
  const approverId = employee?.managerId;

  const baseData = {
    employeeId: caller.employeeId,
    startDate: input.startDate,
    endDate: input.endDate,
    halfDay: input.halfDay,
    reason: input.reason,
    status: "PENDING" as const,
    approverId,
  };

  // Case 1: SICK available === 0 → plain LWP (not auto-generated)
  if (available.lte(0)) {
    const lwp = await tx.leaveRequest.create({
      data: { ...baseData, leaveType: "LEAVE_WITHOUT_PAY", daysRequested: totalDays },
    });
    await logSubmit(tx, caller, lwp, meta);
    return { request: lwp, overflow: null };
  }

  // Case 2: SICK available >= requested → normal SICK
  if (available.gte(totalDays)) {
    await tx.leaveQuota.update({
      where: { id: sickQuota.id },
      data: { pendingDays: { increment: totalDays.toNumber() } },
    });
    const sick = await tx.leaveRequest.create({
      data: { ...baseData, leaveType: "SICK", daysRequested: totalDays, quotaLockedId: sickQuota.id },
    });
    await logSubmit(tx, caller, sick, meta);
    return { request: sick, overflow: null };
  }

  // Case 3: SICK available > 0 but < requested → split
  const overflowDays = totalDays.minus(available);

  await tx.leaveQuota.update({
    where: { id: sickQuota.id },
    data: { pendingDays: { increment: available.toNumber() } },
  });

  const parent = await tx.leaveRequest.create({
    data: { ...baseData, leaveType: "SICK", daysRequested: available, quotaLockedId: sickQuota.id },
  });

  const child = await tx.leaveRequest.create({
    data: {
      ...baseData,
      leaveType: "LEAVE_WITHOUT_PAY",
      daysRequested: overflowDays,
      parentRequestId: parent.id,
      autoGenerated: true,
    },
  });

  await logSubmit(tx, caller, parent, meta);
  await logSubmit(tx, caller, child, meta, "leave.submit_overflow");

  return { request: parent, overflow: child };
}

async function logSubmit(
  tx: TxClient,
  caller: Caller,
  request: { id: string; [key: string]: unknown },
  meta: RequestMeta,
  action = "leave.submit",
) {
  await writeAuditLog(
    {
      actorId: caller.userId,
      action,
      entityType: "LeaveRequest",
      entityId: request.id,
      after: request,
      ipAddress: meta.ip,
      userAgent: meta.userAgent,
    },
    tx,
  );
}
