import { prisma } from "@/lib/prisma";
import type { ReportType, ReportFilters } from "./report-types";

export interface KpiTile { label: string; value: number; format?: "number" | "hours" | "days" }
export interface BucketDatum { label: string; value: number; subValue?: number }

export interface ReportPreview {
  kpis: KpiTile[];
  series: BucketDatum[];
  seriesTitle: string;
}

const TZ = 7;
function bangkokDateKey(d: Date): string {
  return new Date(d.getTime() + TZ * 3600_000).toISOString().slice(0, 10);
}

async function attendancePreview(filters: ReportFilters): Promise<ReportPreview> {
  const fromUtc = new Date(`${filters.dateFrom}T00:00:00.000+07:00`);
  const toUtc = new Date(`${filters.dateTo}T23:59:59.999+07:00`);
  const records = await prisma.attendanceRecord.findMany({
    where: {
      clockedAt: { gte: fromUtc, lte: toUtc },
      ...(filters.departmentId ? { employee: { departmentId: filters.departmentId } } : {}),
    },
    select: { clockedAt: true, clockType: true, employeeId: true, isBackfilled: true },
  });

  const dayBuckets = new Map<string, Set<string>>();
  let backfilled = 0;
  for (const r of records) {
    if (r.isBackfilled) backfilled += 1;
    const key = bangkokDateKey(r.clockedAt);
    if (!dayBuckets.has(key)) dayBuckets.set(key, new Set());
    dayBuckets.get(key)?.add(r.employeeId);
  }
  const totalDays = dayBuckets.size;
  const distinctEmployees = new Set(records.map((r) => r.employeeId)).size;

  const series: BucketDatum[] = Array.from(dayBuckets.entries())
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([date, set]) => ({ label: date, value: set.size }));

  return {
    kpis: [
      { label: "totalRecords", value: records.length },
      { label: "uniqueEmployees", value: distinctEmployees },
      { label: "daysCovered", value: totalDays },
      { label: "backfilledRecords", value: backfilled },
    ],
    series,
    seriesTitle: "attendanceByDay",
  };
}

async function leavePreview(filters: ReportFilters): Promise<ReportPreview> {
  const from = new Date(filters.dateFrom);
  const to = new Date(filters.dateTo + "T23:59:59.999Z");
  const requests = await prisma.leaveRequest.findMany({
    where: { startDate: { lte: to }, endDate: { gte: from }, autoGenerated: false },
    select: { leaveType: true, status: true, daysRequested: true },
  });

  const byType = new Map<string, number>();
  let approved = 0; let pending = 0; let rejected = 0;
  let totalDays = 0;
  for (const r of requests) {
    byType.set(r.leaveType, (byType.get(r.leaveType) ?? 0) + 1);
    if (r.status === "APPROVED") approved++;
    else if (r.status === "PENDING") pending++;
    else if (r.status === "REJECTED") rejected++;
    totalDays += Number(r.daysRequested);
  }

  return {
    kpis: [
      { label: "totalRequests", value: requests.length },
      { label: "approved", value: approved },
      { label: "pending", value: pending },
      { label: "totalDays", value: Math.round(totalDays * 10) / 10, format: "days" },
    ],
    series: Array.from(byType.entries()).map(([type, count]) => ({ label: type, value: count })),
    seriesTitle: "leaveByType",
  };
}

async function otPreview(filters: ReportFilters): Promise<ReportPreview> {
  const from = new Date(filters.dateFrom);
  const to = new Date(filters.dateTo + "T23:59:59.999Z");
  const requests = await prisma.overtimeRequest.findMany({
    where: { date: { gte: from, lte: to } },
    select: { hoursApproved: true, status: true, overtimeType: true },
  });
  const byType = new Map<string, number>();
  let totalHours = 0; let approved = 0; let pending = 0;
  for (const r of requests) {
    const hours = Number(r.hoursApproved ?? 0);
    byType.set(r.overtimeType, (byType.get(r.overtimeType) ?? 0) + hours);
    totalHours += hours;
    if (r.status === "APPROVED") approved++;
    else if (r.status === "PENDING") pending++;
  }
  return {
    kpis: [
      { label: "totalRequests", value: requests.length },
      { label: "approved", value: approved },
      { label: "pending", value: pending },
      { label: "totalHours", value: Math.round(totalHours * 10) / 10, format: "hours" },
    ],
    series: Array.from(byType.entries()).map(([type, hours]) => ({
      label: type,
      value: Math.round(hours * 10) / 10,
    })),
    seriesTitle: "otByType",
  };
}

async function employeePreview(filters: ReportFilters): Promise<ReportPreview> {
  const [total, active, byDept] = await Promise.all([
    prisma.employee.count(),
    prisma.employee.count({ where: { terminationDate: null } }),
    prisma.employee.groupBy({
      by: ["departmentId"],
      _count: { _all: true },
      where: filters.departmentId ? { departmentId: filters.departmentId } : undefined,
    }),
  ]);
  const deptIds = byDept.map((d) => d.departmentId).filter((x): x is string => Boolean(x));
  const depts = await prisma.department.findMany({ where: { id: { in: deptIds } } });
  const deptMap = new Map(depts.map((d) => [d.id, d.name]));

  return {
    kpis: [
      { label: "totalEmployees", value: total },
      { label: "active", value: active },
      { label: "inactive", value: total - active },
      { label: "departments", value: depts.length },
    ],
    series: byDept
      .map((d) => ({ label: deptMap.get(d.departmentId ?? "") ?? "—", value: d._count._all }))
      .sort((a, b) => b.value - a.value),
    seriesTitle: "employeesByDepartment",
  };
}

export async function getReportPreview(type: ReportType, filters: ReportFilters): Promise<ReportPreview> {
  switch (type) {
    case "ATTENDANCE_SUMMARY": return attendancePreview(filters);
    case "LEAVE_SUMMARY": return leavePreview(filters);
    case "OT_SUMMARY": return otPreview(filters);
    case "EMPLOYEE_DIRECTORY": return employeePreview(filters);
  }
}
